### PR TITLE
Add HistogramSeries documentation

### PR DESCRIPTION
**Pull request by VisualMelon**
Add documentation for the `HistogramSeries`.

Things of note:
 - I've included a note indicating that the `HistogramSeries` is only available as pre-release; I don't know if this is a good idea or not. (Because it is pre-release, I have not added the examples to [documentation-examples](https://github.com/oxyplot/documentation-examples); the code for both figures can be seen [in a gist](https://gist.github.com/VisualMelon/c087bcd9ce46c339225561e226276bb5))
 - I was unsure if there was some standard way to produce these documentation images; if not, I've be happy to maintain one
 - I've included documentation on `LabelPlacement`; this might be better placed elsewhere, or otherwise incorporated into the documentation for other series.

### CODE REVIEW

**Comment by objorke** [comment]
Please add the example code to the documentation-examples repo and use the example generator to create the png! :-)

**Comment by VisualMelon** [comment]
Unless I change the documentation-examples repo to use the pre-release MyGet feed, then HistogramSeries cannot presently be included.

Would it make sense to just wait until a release to add the documentation, or would switching the documentation to the pre-release feed be acceptable?

**Comment by objorke** [comment]
I think there should be a stable release before updating the docs

**Comment by objorke** [comment]
thanks!

**Comment by VisualMelon** [comment]
I'll try to sort out the example code later today if I find time and nobody beats me to it.

**Pull request merged**
